DROP TABLE IF EXISTS Collaborate_with;

DROP TABLE IF EXISTS Receives_award;

DROP TABLE IF EXISTS Contracts;

DROP TABLE IF EXISTS Earnings;

DROP TABLE IF EXISTS Rating;

DROP TABLE IF EXISTS Contents;

DROP TABLE IF EXISTS Creators;

DROP TABLE IF EXISTS Collaboration;

DROP TABLE IF EXISTS Awards;

DROP TABLE IF EXISTS Roles;
